name: Build Vanilla Style HUD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: microsoft
          java-version: "25"
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "9.5.1"
      - run: gradle build --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: vanilla-style-hud
          path: build/libs/*.jar
          if-no-files-found: error
